# Generated by Django 4.1.5 on 2023-01-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewal_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
